math_tool:
  llm_endpoint_name: databricks-meta-llama-3-1-405b-instruct

web_search_tool:
  api_key_environment_var : brave_api_key

input_example:
  messages:
  - content: How many Florida fit in India?
    role: user

agent_config:
  llm_endpoint_name: databricks-meta-llama-3-1-405b-instruct
  llm_parameters:
    max_tokens: 2000
    temperature: 0.01

