multi_agent_llm_config:
  llm_endpoint_name: srijit_nair_openai
  llm_parameters:
    max_tokens: 2000
    temperature: 0.01

math_tool:
  llm_endpoint_name: databricks-meta-llama-3-1-405b-instruct

web_search_tool:
  api_key_environment_var : BRAVE_API_KEY

helper_agent_llm_config:
  llm_endpoint_name: databricks-meta-llama-3-1-405b-instruct
  llm_parameters:
    max_tokens: 2000
    temperature: 0.01

genie_agent_config:
  genie_space_id: 01efae624eb11421a468187406487ff4

databricks_resources:
  llm_endpoint_name: databricks-dbrx-instruct
  vector_search_endpoint_name: covid_trials_vs_endpoint

rag_agent_llm_config:
  llm_endpoint_name: databricks-dbrx-instruct
  llm_parameters:
    max_tokens: 1500
    temperature: 0.01
  llm_prompt_template: "You are an assistant that answers questions.
        Use only the information in context to answer the question at the end.
        Some pieces of context may be irrelevant, in which case you should not use them to form the answer.
        Only answer question from the context, do not add anymore information. 
        If the question is not relevant to COVID Trials, only respond with 'Irrelevant Question'.
        \n\nContext: {context},
        \n\nQuestion:{query}"
  llm_prompt_template_variables:
  - context
  - query

retriever_config:
  vector_search_endpoint_name: covid_trials_vs_endpoint
  vector_search_index: main.covid_trials.covid_data_title_index
  workspace_url_environment_var: WORKSPACE_URL
  pat_environment_var: VECTOR_SEARCH_PAT
  client_id_environment_var: VECTOR_SEARCH_CLIENT_ID
  client_secret_environment_var: VECTOR_SEARCH_CLIENT_SECRET
  text_column: "title"
  retrieve_columns: ["title","interventions","url"]
  parameters:
      k: 3
      query_type: ann

input_example:
  messages:
  - content: How many Florida fit in India?
    role: user