multi_agent_llm_config:
  llm_endpoint_name: srijit_nair_openai
  llm_parameters:
    max_tokens: 2000
    temperature: 0.01

web_search_api_key_environment_var : BRAVE_API_KEY
helper_agent_config_environment_var : HELPER_AGENT_CONFIG_FILE
rag_agent_config_environment_var : RAG_AGENT_CONFIG_FILE
genie_agent_config_environment_var : GENIE_AGENT_CONFIG_FILE
multi_agent_config_environment_var : MULTI_AGENT_CONFIG_FILE

input_example:
  messages:
  - content: How many covid trials was completed in capital of France?
    role: user