databricks_resources:
  llm_endpoint_name: databricks-dbrx-instruct
  vector_search_endpoint_name: covid_trials_vs_endpoint

input_example:
  messages:
  - content: Which studies research on pregnancy and covid?
    role: user

llm_config:
  llm_endpoint_name: databricks-dbrx-instruct
  llm_parameters:
    max_tokens: 1500
    temperature: 0.01
  llm_prompt_template: "You are an assistant that answers questions.
        Use only the information in context to answer the question at the end.
        Some pieces of context may be irrelevant, in which case you should not use them to form the answer.
        Only answer question from the context, do not add anymore information. 
        If the question is not relevant to COVID Trials, only respond with 'Irrelevant Question'.
        \n\nContext: {context},
        \n\nQuestion:{query}"
  llm_prompt_template_variables:
  - context
  - query

retriever_config:
  vector_search_endpoint_name: covid_trials_vs_endpoint
  vector_search_index: main.covid_trials.covid_data_title_index  
  text_column: "title"
  retrieve_columns: ["title","interventions","url"]
  parameters:
      k: 3
      query_type: ann