multi_agent_config:
  llm_config:
    llm_endpoint_name: srijit_nair_openai
    llm_parameters:
      max_tokens: 2000
      temperature: 0.01

  input_example:
    messages:
    - content: How many covid trials was completed in capital of France?
      role: user

genie_agent_config:
  genie_space_id: 01efa5d3862c1317969a569e3cdfcb1c
  genie_space_sql_warehouse_id: b721abe0cc790b1f


helper_agent_config:
  math_tool:
    llm_endpoint_name: srijit_nair_openai

  web_search_tool:
    api_key_environment_var : BRAVE_API_KEY

  helper_agent_llm_config:
    llm_endpoint_name: srijit_nair_openai
    llm_parameters:
      max_tokens: 2000
      temperature: 0.01

rag_agent_config:
  llm_endpoint_name: srijit_nair_openai
  
  llm_parameters:
    max_tokens: 1500
    temperature: 0.01
  
  llm_prompt_template: "You are an assistant that answers questions.
        Use only the information in context to answer the question at the end.
        Some pieces of context may be irrelevant, in which case you should not use them to form the answer.
        Only answer question from the context, do not add anymore information. 
        If the question is not relevant to COVID Trials, only respond with 'Irrelevant Question'.
        \n\nContext: {supporting_documents},
        \n\nQuestion:{query}"

  retriever_config:
    vector_search_endpoint_name: covid_trials_vs_endpoint
    vector_search_index: main.covid_trials.covid_data_title_index
    text_column: "title"
    retrieve_columns: ["title","interventions","url"]
    parameters:
        k: 3
        query_type: ann